name: On PR

on:
  pull_request:
    branches:
      - main
      - develop
      - v3
      - v5
      - v6

jobs:
  dependency-review-pr:
    uses: onecx/ci-common/.github/workflows/dependency-review.yml@v1
    secrets: inherit
    with:
      failOnSeverity: "high"

  ci-pr:
    uses: ./.github/workflows/ci-common.yml
    secrets: inherit
